// @ts-check
// `@type` JSDoc annotations allow editor autocompletion and type checking
// (when paired with `@ts-check`).
// There are various equivalent ways to declare your Docusaurus config.
// See: https://docusaurus.io/docs/api/docusaurus-config

import "dotenv/config";

import { themes as prismThemes } from "prism-react-renderer";
import webpack from "webpack";
// import { version } from "react";
// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const replaceAutogeneratedWithSidebarFile = (sidebarItems) => {
  return sidebarItems.map((item) => {
    if (Array.isArray(item.items)) {
      if (item.customProps?.autogenerate === false) {
        const fs = require("fs");
        const path = require("path");
        const sidebarFilePath = path.resolve(item.customProps.sidebarFile);
        const sidebarModule = require(sidebarFilePath);
        item.items = sidebarModule.default || sidebarModule;
        return item;
      } else {
        item.items = replaceAutogeneratedWithSidebarFile(item.items);
        return item;
      }
    }

    return item;
  });
};

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Talent Protocol",
  tagline: "The Reputation Layer for the New Internet",
  favicon: "img/favicon.ico",

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // Set the production url of your site here
  url: "https://docs2.talentprotocol.com",
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: "/",

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "talentprotocol", // Usually your GitHub org/user name.
  projectName: "public-docs", // Usually your repo name.
  deploymentBranch: "main", // The branch that GitHub pages will deploy from.
  trailingSlash: false,

  onBrokenLinks: "throw",
  onBrokenMarkdownLinks: "throw",

  // Even if you don't use internationalization, you can use this field to set
  // useful metadata like html lang. For example, if your site is Chinese, you
  // may want to replace "en" with "zh-Hans".
  i18n: {
    defaultLocale: "en",
    locales: ["en"],
  },

  markdown: {
    mermaid: true,
  },

  plugins: [
    function defineEnvPlugin() {
      return {
        name: "define-env-plugin",
        configureWebpack() {
          return {
            plugins: [
              new webpack.DefinePlugin({
                'process.env.TALENT_PROTOCOL_API_KEY': JSON.stringify(process.env.TALENT_PROTOCOL_API_KEY || ''),
              }),
            ],
          };
        },
      };
    },
    "./plugins/docusaurus-plugin-gen-data-points",
    [
      "@docusaurus/plugin-content-pages",
      {
        path: "src/pages",
        routeBasePath: "",
        // include: ['**/*.{js,jsx,ts,tsx,md,mdx}'],
        // exclude: [
        //   '**/_*.{js,jsx,ts,tsx,md,mdx}',
        //   '**/_*/**',
        //   '**/*.test.{js,jsx,ts,tsx}',
        //   '**/__tests__/**',
        // ],
        // mdxPageComponent: '@theme/MDXPage',
        // remarkPlugins: [],
        // rehypePlugins: [],
        // beforeDefaultRemarkPlugins: [],
        // beforeDefaultRehypePlugins: [],
      },
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        path: "docs",
        breadcrumbs: true,
        routeBasePath: "/docs",
        sidebarPath: "./sidebars.js",
        docItemComponent: "@theme/ApiItem",
        async sidebarItemsGenerator({ defaultSidebarItemsGenerator, ...args }) {
          const sidebarItems = await defaultSidebarItemsGenerator(args);
          return replaceAutogeneratedWithSidebarFile(sidebarItems);
        },
        remarkPlugins: [require("remark-gfm")],
      },
    ],
    [
      "@docusaurus/plugin-sitemap",
      {
        lastmod: "date",
        changefreq: "weekly",
        priority: 0.5,
        ignorePatterns: ["/tags/**"],
        filename: "sitemap.xml",
      },
    ],
    [
      "@docusaurus/theme-classic",
      /** @type {import('@docusaurus/theme-classic').Options} */
      ({
        customCss: "./src/css/custom.css",
      }),
    ],
    [
      "docusaurus-plugin-openapi-docs",
      {
        id: "api",
        docsPlugin: "@docusaurus/plugin-content-docs",
        docsPluginId: "default",

        config: {
          talentProtocolApi: {
            specPath: "https://api.talentprotocol.com/api-docs/v3/swagger.json",
            outputDir: "docs/developers/talent-api/api-reference",
            sidebarOptions: {
              groupPathsBy: "tag",
            },
          },
        },
      },
    ],
  ],

  // presets: [
  //   [
  //     'classic',
  //     /** @type {import('@docusaurus/preset-classic').Options} */
  //     ({
  //       docs: {
  //         sidebarPath: './sidebars.js',
  //         // Please change this to your repo.
  //         // Remove this to remove the "edit this page" links.
  //         //editUrl:
  //         //  'https://github.com/talentprotocol/public-docs/tree/main/packages/create-docusaurus/templates/shared/',
  //       },
  //       blog: {
  //         showReadingTime: true,
  //         feedOptions: {
  //           type: ['rss', 'atom'],
  //           xslt: true,
  //         },
  //         // Please change this to your repo.
  //         // Remove this to remove the "edit this page" links.
  //         //editUrl:
  //         //  'https://github.com/talentprotocol/public-docs/tree/main/packages/create-docusaurus/templates/shared/',
  //         // Useful options to enforce blogging best practices
  //         onInlineTags: 'warn',
  //         onInlineAuthors: 'warn',
  //         onUntruncatedBlogPosts: 'warn',
  //       },
  //       theme: {
  //         customCss: './src/css/custom.css',
  //       },
  //     }),
  //   ]
  // ],

  themes: [
    "docusaurus-theme-openapi-docs",
    "@docusaurus/theme-mermaid",
    "@docusaurus/theme-search-algolia",
  ],


  themeConfig:
    /** @type {import('@docusaurus/types').ThemeConfig} */
    ({
      // Replace with your project's social card
      image: "img/talent-protocol-og-image.jpg",
      navbar: {
        title: "Talent Protocol",
        logo: {
          alt: "Talent Protocol Logo",
          src: "img/talent-protocol-logo.avif",
          href: "/docs/developers/get-started",
        },
      },
      // footer: {
      //   style: 'dark',
      //   links: [
      //     {
      //       title: 'Community',
      //       items: [
      //         {
      //           label: 'Farcaster',
      //           href: 'https://warpcast.com/talent',
      //         },
      //         {
      //           label: 'X',
      //           href: 'https://x.com/TalentProtocol',
      //         },
      //         {
      //           label: 'Discord',
      //           href: 'https://discord.com/invite/talentprotocol',
      //         },
      //         {
      //           label: 'Telegram',
      //           href: 'https://t.me/talentprotocol',
      //         }
      //       ],
      //     },
      //     {
      //       title: 'More',
      //       items: [
      //         {
      //           label: 'App',
      //           to: '/app.talentprotocol.com',
      //         },
      //         {
      //           label: 'GitHub',
      //           href: 'https://github.com/talentprotocol/public-docs',
      //         },
      //       ],
      //     },
      //   ],
      //   copyright: `Copyright © 2020 - ${new Date().getFullYear()} Talent Protocol. Built with Docusaurus.`,
      // },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ["solidity", "ruby", "yaml", "bash"],
        defaultLanguage: "bash",
      },
      colorMode: {
        defaultMode: "dark",
        disableSwitch: false,
        respectPrefersColorScheme: true,
      },
      docs: {
        versionPersistence: "localStorage",
        sidebar: {
          hideable: true,
          autoCollapseCategories: true,
        },
      },
      algolia: {
        // The application ID provided by Algolia
        appId: "HV8WZA9LV0",

        // Public API key: it is safe to commit it
        apiKey: "f73f4f9bdda3359c11ab96c499d1b566",

        indexName: "talentprotocol",

        // Optional: see doc section below
        contextualSearch: true,

        // Optional: Specify domains where the navigation should occur through window.location instead on history.push. Useful when our Algolia config crawls multiple documentation sites and we want to navigate with window.location.href to them.
        // externalUrlRegex: "external\\.com|domain\\.com",

        // Optional: Replace parts of the item URLs from Algolia. Useful when using the same search index for multiple deployments using a different baseUrl. You can use regexp or string in the `from` param. For example: localhost:3000 vs myCompany.com/docs
        // replaceSearchResultPathname: {
        // from: "/docs/", // or as RegExp: /\/docs\//
        // to: "/",
        // },

        // Optional: Algolia search parameters
        searchParameters: {},

        // Optional: path for search page that enabled by default (`false` to disable it)
        searchPagePath: "false",

        // Optional: whether the insights feature is enabled or not on Docsearch (`false` by default)
        insights: false,
      },
    }),
};

export default config;
